import type { Click, Conversion, Transaction } from "@/types";

// Small sample of tracking data, mainly to demonstrate the shape of
// Click -> Conversion -> Transaction. A real implementation would have
// many thousands of these rows generated by the tracking pixel/redirect.
export const clicks: Click[] = [
  { id: "click_01", campaignId: "camp_01", publisherId: "pub_01", clickId: "clk_a1b2c3", timestamp: "2026-09-10T08:12:00Z", geo: "Denmark" },
  { id: "click_02", campaignId: "camp_07", publisherId: "pub_03", clickId: "clk_d4e5f6", timestamp: "2026-09-11T14:40:00Z", geo: "Norway" },
  { id: "click_03", campaignId: "camp_12", publisherId: "pub_06", clickId: "clk_g7h8i9", timestamp: "2026-09-12T09:05:00Z", geo: "Norway" },
];

export const conversions: Conversion[] = [
  { id: "conv_01", clickId: "clk_a1b2c3", campaignId: "camp_01", publisherId: "pub_01", advertiserId: "adv_01", commission: 320, status: "approved", timestamp: "2026-09-10T08:30:00Z" },
  { id: "conv_02", clickId: "clk_d4e5f6", campaignId: "camp_07", publisherId: "pub_03", advertiserId: "adv_04", commission: 145, status: "pending", timestamp: "2026-09-11T15:02:00Z" },
  { id: "conv_03", clickId: "clk_g7h8i9", campaignId: "camp_12", publisherId: "pub_06", advertiserId: "adv_07", commission: 210, status: "approved", timestamp: "2026-09-12T09:20:00Z" },
];

export const transactions: Transaction[] = [
  { id: "txn_01", dealId: "deal_01", amount: 320, type: "payout", status: "completed", timestamp: "2026-09-15T00:00:00Z" },
  { id: "txn_02", dealId: "deal_02", amount: 145, type: "payout", status: "pending", timestamp: "2026-09-15T00:00:00Z" },
  { id: "txn_03", dealId: "deal_04", amount: 210, type: "payout", status: "completed", timestamp: "2026-09-15T00:00:00Z" },
];
